pipeline {
    agent { label 'principal' }

    environment {
        DOCKER_IMAGE = 'flutter-web-app'
        DOCKER_CONTAINER = 'flutter-web-container'
        PORT = '8081'
    }

    stages {
        stage('Clonar Dockerfile desde Repo B') {
          steps {
            // Clonamos el propio repo que contiene el Dockerfile
            sh 'git clone --depth=1 --branch main https://github.com/Lnavarrete14/Atik_devops_configuration.git temp_config_repo'
            sh 'cp temp_config_repo/portal_vips/dockerfile Dockerfile'
            sh 'rm -rf temp_config_repo'
          }
        }
    
        stage('Checkout código del proyecto (Repo A)') {
          steps {
            checkout scm
          }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Deploy Docker Container') {
            steps {
                script {
                    sh "docker rm -f $DOCKER_CONTAINER || true"
                    sh "docker run -d --restart always --name $DOCKER_CONTAINER -p $PORT:80 $DOCKER_IMAGE"
                }
            }
        }
    }
}
