pipeline {
    agent { label 'principal' }

    environment {
        DOCKER_IMAGE = 'flutter-web-app'
        DOCKER_CONTAINER = 'flutter-web-container'
        PORT = '8080'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Deploy Docker Container') {
            steps {
                script {
                    sh "docker rm -f $DOCKER_CONTAINER || true"
                    sh "docker run -d --restart always --name $DOCKER_CONTAINER -p $PORT:80 $DOCKER_IMAGE"
                }
            }
        }
    }
}
