pipeline {
    agent { label 'principal' }

    environment {
        DOCKER_IMAGE = 'flutter-web-app'
        DOCKER_CONTAINER = 'flutter-web-container'
        PORT = '8081'
    }

    stages {
        stage('Checkout código del proyecto') {
          steps {
            checkout scm // trae el código de Repo A (el que ejecuta el pipeline)
          }
        }
    
        stage('Usar Dockerfile de Repo B') {
          steps {
            // Copiamos el Dockerfile desde Repo B al root del workspace
            sh 'cp portal_vips/dockerfile Dockerfile'
          }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Deploy Docker Container') {
            steps {
                script {
                    sh "docker rm -f $DOCKER_CONTAINER || true"
                    sh "docker run -d --restart always --name $DOCKER_CONTAINER -p $PORT:80 $DOCKER_IMAGE"
                }
            }
        }
    }
}
